### ISSUE TITLE
Lowercase require causes problem with case sensitivity on Ubuntu LInux

### ISSUE THREAD

**Issue by elloserafim** [JJLongoria/aura-helper#32]
Thank you for the amazing work, this is an extension I am looking forward to try.
But I am unable to activate the extension and it does not work on my computer for a reason that others may experience.
In my extension log (exthost.log) it reads:

```
[2020-09-01 19:04:01.750] [exthost] [info] eager extensions activated
[2020-09-01 19:04:18.998] [exthost] [info] ExtensionService#_doActivateExtension Kanko.aura-helper {"startup":false,"extensionId":{"value":"Kanko.aura-helper","_lower":"kanko.aura-helper"},"activationEvent":"workspaceContains:sfdx-project.json"}
[2020-09-01 19:04:18.998] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/ello/.vscode/extensions/kanko.aura-helper-2.2.1/extension.js
[2020-09-01 19:04:19.060] [exthost] [error] Activating extension Kanko.aura-helper failed due to an error:
[2020-09-01 19:04:19.063] [exthost] [error] Error: Cannot find module './nodes/fornode'
Require stack:
- /home/ello/.vscode/extensions/kanko.aura-helper-2.2.1/resources/scripts/languages/apex/parser.js
- /home/ello/.vscode/extensions/kanko.aura-helper-2.2.1/resources/scripts/languages/apex/index.js
- /home/ello/.vscode/extensions/kanko.aura-helper-2.2.1/resources/scripts/languages/index.js
- /home/ello/.vscode/extensions/kanko.aura-helper-2.2.1/resources/scripts/providers/utils.js
- /home/ello/.vscode/extensions/kanko.aura-helper-2.2.1/resources/scripts/providers/apexCompletionProvider.js
- /home/ello/.vscode/extensions/kanko.aura-helper-2.2.1/resources/scripts/providers/index.js
- /home/ello/.vscode/extensions/kanko.aura-helper-2.2.1/extension.js
- /snap/code/42/usr/share/code/resources/app/out/vs/loader.js
- /snap/code/42/usr/share/code/resources/app/out/bootstrap-amd.js
- /snap/code/42/usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:764:15)
	at Module._load (internal/modules/cjs/loader.js:669:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/snap/code/42/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
	at Function.i._load (/snap/code/42/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
	at Function.n._load  [...]
	at /snap/code/42/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:612:374
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async h.$activate (/snap/code/42/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:882:193)
```

(I am abbreviating the log here)

It happens that in repo file aura-helper/resources/scripts/languages/apex/parser.js/ line 27 ForNode module is imported like 'fornode' :

```
const WhileNode = require('./nodes/whileNode');
const ForNode = require('./nodes/fornode');    //  * Note all lowercase here *
const ForeachNode = require('./nodes/foreachNode');
 
```

whereas the file name is `./node/forNode.js`, like other files in the same folder. This may note be a problem on Windows, but it may cause problems on case-sensitive systems.

**Comment by JJLongoria** [comment]
Hi!
Sorry for the delay in reply. I published a new version with this error fixed (and some new features). 

Thanks for report and enjoy the app.
